defaults:
  - env: chainball_11_4_hard
  - agents: tab_mappo
  - run: train_1m
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: hydra_slurm
  - _self_

hydra:
  launcher:
    timeout_min: 240
    cpus_per_task: 1
    array_parallelism: 256
    mem_per_cpu: 1G
  sweeper:
    params:
      ++seed: range(0,16)

name: chainball
seed: 1
zoo_path: chainball_zoo/zoo

agents:
  gamma: 0.99
  lr:
    actor: 4e-3
    critic: 8e-3
  ent_coef: 4e-2
  n_steps: 4
  n_epochs: 32
  save_to_zoo: false
  n_agents: 4
  agents:
    - agent_id: alice
      save_to_zoo: false
    - agent_id: bob
      save_to_zoo: false
    - agent_id: carol
      save_to_zoo: false
    - agent_id: dave
      save_to_zoo: false
  exp_buffer:
    size: 0
    replacement_prob: 0

logger:
  mode: online
  enable_render: false
  model_save_period:
    val: 0.1
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
