defaults:
  - env: chainball_11_4_att
  - agents: tab_ippo
  - run: train_100k
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: hydra_slurm
  - _self_

hydra:
  launcher:
    timeout_min: 60
    cpus_per_task: 1
    array_parallelism: 256
    mem_per_cpu: 1G
  sweeper:
    params:
      env: chainball_11_4_att,chainball_11_4_def
      ++seed: range(0,4)

name: chainball
seed: 1
zoo_path: chainball_zoo/zoo

agents:
  ent_coef: 4e-3
  lr:
    actor: 2e-2
    critic: 4e-2
  gamma: 0.99
  n_epochs: 16
  save_to_zoo: true
  n_agents: 2
  agents:
    - agent_id: alice
      save_to_zoo: true
    - agent_id: bob
      save_to_zoo: true

logger:
  mode: online
  enable_render: false
  model_save_period:
    val: 0.1
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
