defaults:
  - env: chainball_11_4_hard
  - agents: tab_mappo
  - run: train_1m
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: slurm_sweep
  - _self_

hydra:
  launcher:
    timeout_min: 100
    cpus_per_task: 1
    array_parallelism: 256
    mem_per_cpu: 1G
    additional_parameters: {"nice": 100}
  sweeper:
    optim:
      optimizer: RandomSearch
      budget: 256
      num_workers: 64
      noisy: true
      maximize: false
      seed: null
      max_failure_rate: 0.1
    parametrization:
      agents.ent_coef:
        lower: 1e-5
        upper: 1e-2
        log: true
      agents.lr.actor:
        lower: 1e-4
        upper: 1
        log: true
          agents.
      agents.gamma:
        - 0.99
        - 0.999
      agents.n_epochs:
        - 4
        - 8
        - 16
        - 32

name: chainball
seed: 1
zoo_path: chainball_zoo/zoo

agents:
  lr:
    critic: ${eval:'2*${agents.lr.actor}'}
  save_to_zoo: false
  n_agents: 4
  agents:
    - agent_id: alice
      save_to_zoo: true
    - agent_id: bob
      save_to_zoo: true
    - agent_id: carol
      save_to_zoo: true
    - agent_id: dave
      save_to_zoo: true
  exp_buffer:
    size: 0
    replacement_prob: 0

logger:
  log_chainball_auc: true
  mode: online
  enable_render: false
  model_save_period:
    val: 0.5
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
