defaults:
  - env: cooking_base
  - agents: bp_ippo
  - run: train_0
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: hydra_slurm
  - override agents/medoe/classifier: mlp_cooking
  - _self_

hydra:
  launcher:
    timeout_min: 1440
    cpus_per_task: 4
    array_parallelism: 24
    mem_per_cpu: 2G
  sweeper:
    params:
      agents.medoe.zoo_alice: milan-everitt,lisabeth-wainwright,aja-bacon,brett-henry
      agents.medoe.zoo_bob: marilee-dyerson,margot-quinnell,cathrine-laing,deeanna-helm
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${agents.medoe.zoo_alice}_${agents.medoe.zoo_bob}_${seed}

name: cooking
seed: 1
zoo_path: cooking_zoo/zoo

agents:
  zoo_path: ${zoo_path}
  model:
    actor:
      - 256
      - 128
    critic:
      - 256
      - 128
  ent_coef: 8e-3
  lr:
    actor: 2e-4
    critic: 4e-4
  n_steps: 16
  save_to_zoo: false
  n_agents: 2
  agents:
    - agent_id: alice
      save_to_zoo: true
      zoo_name: ${agents.medoe.zoo_alice}
    - agent_id: bob
      save_to_zoo: true
      zoo_name: ${agents.medoe.zoo_bob}
  exp_buffer:
    size: 0
    replacement_prob: 0
  medoe:
    zoo_alice: ZOO_ALICE
    zoo_bob: ZOO_BOB

logger:
  mode: offline
  enable_render: false
  model_save_period:
    val: 0.1
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
