defaults:
  - env: cooking_split_room_osrd
  - agents: ippo
  - run: train_0
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: hydra_slurm
  - _self_

hydra:
  launcher:
    timeout_min: 1440
    cpus_per_task: 1
    array_parallelism: 128
    mem_per_cpu: 1G
  sweeper:
    params:
      env: cooking_split_room_osld,cooking_split_room_osrd
      pseudotag: MEDoE,MEDoE_noBP,PS,PS_noBP
      zoo.alice: milan-everitt,lisabeth-wainwright,aja-bacon,brett-henry
      zoo.bob: marilee-dyerson,margot-quinnell,cathrine-laing,deeanna-helm


name: cooking
seed: 1
zoo_path: cooking_zoo/zoo

run:
  n_eval_episodes: 100
env:
  n_parallel: 1
  n_cpus: 1

zoo:
  alice: milan-everitt
  bob: marilee-dyerson

pseudotag: MEDoE
checkpoint_dir: cooking_forget/${pseudotag}/${zoo.alice}_${zoo.bob}/saved_models/

agents:
  model:
    actor:
      - 256
      - 128
    critic:
      - 256
      - 128
  ent_coef: 8e-3
  lr:
    actor: 4e-4
    critic: 8e-4
  n_steps: 16
  n_epochs: 16
  save_to_zoo: false
  n_agents: 2
  agents:
    - agent_id: alice
      save_to_zoo: true
      source_id: alice
    - agent_id: bob
      save_to_zoo: true
      source_id: bob
  exp_buffer:
    size: 0
    replacement_prob: 0

logger:
  mode: online
  enable_render: false
  model_save_period:
    val: 0.2
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
