defaults:
    - env: vmas_football_full
    - agents: mappo
    - run: train_100m
    - logger: default_logger
    - env@eval.env: ${env}
    - hydra: hydra_slurm
    - _self_

hydra:
  launcher:
    timeout_min: 10080
    cpus_per_task: 8
    array_parallelism: 32
    mem_per_cpu: 2G
  sweeper:
    params:
      ++seed: range(0,16)

name: vmas
seed: 1
zoo_path: vmas_zoo/zoo

run:
  max_training_steps: 200_000_000

agents:
  model:
    actor:
      - 256
      - 256
      - 128
    critic:
      - 256
      - 256
      - 128
  gamma: 0.999
  lr:
    actor: 4e-3
    critic: 8e-3
  ent_coef: 4e-3
  n_steps: 64
  n_epochs: 8
  n_agents: 4
  save_to_zoo: false
  agents:
      - agent_id: LB
        save_to_zoo: false
      - agent_id: RB
        save_to_zoo: false
      - agent_id: LF
        save_to_zoo: false
      - agent_id: RF
        save_to_zoo: false

logger:
  mode: online
  enable_render: false
  model_save_period:
    val: 0.05
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.05
