defaults:
  - env: vmas_football_full
  - agents: bp_ippo
  - run: train_0
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: hydra_slurm
  - override agents/medoe/classifier: mlp_vmas
  - _self_

hydra:
  launcher:
    timeout_min: 3600
    cpus_per_task: 4
    array_parallelism: 24
    mem_per_cpu: 1G
  sweeper:
    params:
      +zoo_att: vmas_att_0, vmas_att_1, vmas_att_2, vmas_att_3
      +zoo_def: vmas_def_0, vmas_def_1, vmas_def_2, vmas_def_3
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${zoo_def.RB}_${zoo_att.RF}

name: vmas
seed: 1
zoo_path: vmas_zoo/zoo

agents:
  zoo_path: ${zoo_path}
  model:
    actor:
      - 256
      - 256
      - 128
    critic:
      - 256
      - 256
      - 128
  save_to_zoo: false
  n_agents: 4
  agents:
    - agent_id: LB
      save_to_zoo: false
      zoo_name: ${zoo_def.LB}
    - agent_id: RB
      save_to_zoo: false
      zoo_name: ${zoo_def.RB}
    - agent_id: LF
      save_to_zoo: false
      zoo_name: ${zoo_att.LF}
    - agent_id: RF
      save_to_zoo: false
      zoo_name: ${zoo_att.RF}
  exp_buffer:
    size: 0
    replacement_prob: 0
  medoe:
    zoo_LB: ${zoo_def.LB}
    zoo_RB: ${zoo_def.RB}
    zoo_LF: ${zoo_att.LF}
    zoo_RF: ${zoo_att.RF}

logger:
  mode: offline
  enable_render: false
  project: vmas-medoe
  group: mlp_train
  model_save_period:
    val: 0.1
  eval_period:
    val: 0.02
  train_metric_period:
    val: 0.02
