defaults:
  - env: vmas_football_att
  - agents: ippo
  - run: train_50m
  - logger: default_logger
  - env@eval.env: ${env}
  - hydra: slurm_sweep
  - _self_

hydra:
  launcher:
    timeout_min: 1000
    cpus_per_task: 8
    array_parallelism: 24
    mem_per_cpu: 1G
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${logger.group}
    subdir: all
  sweeper:
    optim:
      optimizer: RandomSearch
      budget: 64
      num_workers: 24
      noisy: true
      maximize: true
      seed: null
      max_failure_rate: 0.1
    parametrization:
      agents.lr.actor:
        lower: 3e-5
        upper: 1e-2
        log: true
      agents.ent_coef:
        lower: 1e-5
        upper: 1e-3
        log: true
      agents.n_epochs:
        - 2
        - 4
        - 8
        - 16
      agents.n_steps:
        - 16
        - 32
        - 64

name: vmas
seed: 1
zoo_path: vmas_zoo/zoo

agents:
  model:
    actor:
      - 256
      - 256
    critic:
      - 256
      - 256
  ent_coef: 3e-4
  lr:
    actor: 1e-4
    critic: ${eval:'2*${agents.lr.actor}'}
  n_steps: 32
  save_to_zoo: false
  n_agents: 2
  agents:
    - agent_id: ${eval:'"LB" if "def" in "${env.name}" else "LF"'}
      save_to_zoo: false
    - agent_id: ${eval:'"RB" if "def" in "${env.name}" else "RF"'}
      save_to_zoo: false
  exp_buffer:
    size: 0
    replacement_prob: 0.1

logger:
  log_vmas_auc: true
  mode: online
  enable_render: false
  project: vmas-medoe
  group: drill
  model_save_period:
    val: 0.2
  eval_period:
    val: 0.05
  train_metric_period:
    val: 0.02
